const projects = [
    { src: 'PROJETOS/BODYAGE/1.png', category: 'Rótulos', title: 'BODYAGE' },
    { src: 'PROJETOS/BODYAGE/3.png', category: 'Rótulos', title: 'BODYAGE' },
    { src: 'PROJETOS/BODYAGE/4.png', category: 'Rótulos', title: 'BODYAGE' },
    { src: 'PROJETOS/BODYAGE/5.png', category: 'Rótulos', title: 'BODYAGE' },
    { src: 'PROJETOS/BODYAGE/6.png', category: 'Rótulos', title: 'BODYAGE' },
    { src: 'PROJETOS/BODYAGE/7.png', category: 'Rótulos', title: 'BODYAGE' },
    { src: 'PROJETOS/CALMALIV/1.png', category: 'Rótulos', title: 'CALMALIV' },
    { src: 'PROJETOS/CALMALIV/2.png', category: 'Rótulos', title: 'CALMALIV' },
    { src: 'PROJETOS/COLÁGENO/1.png', category: 'Rótulos', title: 'COLÁGENO' },
    { src: 'PROJETOS/COLÁGENO/2.png', category: 'Rótulos', title: 'COLÁGENO' },
    { src: 'PROJETOS/COLÁGENO/3.png', category: 'Rótulos', title: 'COLÁGENO' },
    { src: 'PROJETOS/COLÁGENO/4.png', category: 'Rótulos', title: 'COLÁGENO' },
    { src: 'PROJETOS/FITOVIRON/1.png', category: 'Rótulos', title: 'FITOVIRON' },
    { src: 'PROJETOS/FITOVIRON/2.png', category: 'Rótulos', title: 'FITOVIRON' },
    { src: 'PROJETOS/FITOVIRON/4.png', category: 'Rótulos', title: 'FITOVIRON' },
    { src: 'PROJETOS/GLOW/1.png', category: 'Rótulos', title: 'GLOW' },
    { src: 'PROJETOS/GLOW/2.png', category: 'Rótulos', title: 'GLOW' },
    { src: 'PROJETOS/GLOW/3.png', category: 'Rótulos', title: 'GLOW' },
    { src: 'PROJETOS/GLOW/4.png', category: 'Rótulos', title: 'GLOW' },
    { src: 'PROJETOS/GLOW/5.png', category: 'Rótulos', title: 'GLOW' },
    { src: 'PROJETOS/GLOW/6.png', category: 'Rótulos', title: 'GLOW' },
    { src: 'PROJETOS/HARAS SB HORSE/1.1.png', category: 'Marcas', title: 'HARAS SB HORSE' },
    { src: 'PROJETOS/HARAS SB HORSE/2.png', category: 'Marcas', title: 'HARAS SB HORSE' },
    { src: 'PROJETOS/HARAS SB HORSE/3.png', category: 'Marcas', title: 'HARAS SB HORSE' },
    { src: 'PROJETOS/HARAS SB HORSE/4.png', category: 'Marcas', title: 'HARAS SB HORSE' },
    { src: 'PROJETOS/HARAS SB HORSE/5.png', category: 'Marcas', title: 'HARAS SB HORSE' },
    { src: 'PROJETOS/HARAS SB HORSE/6.png', category: 'Marcas', title: 'HARAS SB HORSE' },
    { src: 'PROJETOS/HYALUROSTEO/2.png', category: 'Rótulos', title: 'HYALUROSTEO' },
    { src: 'PROJETOS/HYALUROSTEO/3.png', category: 'Rótulos', title: 'HYALUROSTEO' },
    { src: 'PROJETOS/HYALUROSTEO/4.png', category: 'Rótulos', title: 'HYALUROSTEO' },
    { src: 'PROJETOS/HYALUROSTEO/5.png', category: 'Rótulos', title: 'HYALUROSTEO' },
    { src: 'PROJETOS/LOJA DAS CAPINHAS/1.png', category: 'Marcas', title: 'LOJA DAS CAPINHAS' },
    { src: 'PROJETOS/LOJA DAS CAPINHAS/2.png', category: 'Marcas', title: 'LOJA DAS CAPINHAS' },
    { src: 'PROJETOS/LOJA DAS CAPINHAS/3.png', category: 'Marcas', title: 'LOJA DAS CAPINHAS' },
    { src: 'PROJETOS/LOJA DAS CAPINHAS/4.png', category: 'Marcas', title: 'LOJA DAS CAPINHAS' },
    { src: 'PROJETOS/MP/1.png', category: 'Marcas', title: 'MP' },
    { src: 'PROJETOS/MP/10.png', category: 'Marcas', title: 'MP' },
    { src: 'PROJETOS/MP/11.png', category: 'Marcas', title: 'MP' },
    { src: 'PROJETOS/MP/2.png', category: 'Marcas', title: 'MP' },
    { src: 'PROJETOS/MP/3.png', category: 'Marcas', title: 'MP' },
    { src: 'PROJETOS/MP/4.png', category: 'Marcas', title: 'MP' },
    { src: 'PROJETOS/MP/5.png', category: 'Marcas', title: 'MP' },
    { src: 'PROJETOS/MP/6.png', category: 'Marcas', title: 'MP' },
    { src: 'PROJETOS/MP/7.png', category: 'Marcas', title: 'MP' },
    { src: 'PROJETOS/MP/8.png', category: 'Marcas', title: 'MP' },
    { src: 'PROJETOS/MP/9.png', category: 'Marcas', title: 'MP' },
    { src: 'PROJETOS/OSTEO PRO CALCIUM/1.png', category: 'Rótulos', title: 'OSTEO PRO CALCIUM' },
    { src: 'PROJETOS/OSTEO PRO CALCIUM/2.png', category: 'Rótulos', title: 'OSTEO PRO CALCIUM' },
    { src: 'PROJETOS/OSTEO PRO CALCIUM/3.png', category: 'Rótulos', title: 'OSTEO PRO CALCIUM' },
    { src: 'PROJETOS/TREONMAG/1.png', category: 'Rótulos', title: 'TREONMAG' },
    { src: 'PROJETOS/TREONMAG/2.png', category: 'Rótulos', title: 'TREONMAG' },
    { src: 'PROJETOS/TREONMAG/3.png', category: 'Rótulos', title: 'TREONMAG' },
    { src: 'PROJETOS/UPRADE/1.png', category: 'Rótulos', title: 'UPRADE' },
    { src: 'PROJETOS/UPRADE/2.png', category: 'Rótulos', title: 'UPRADE' },
    { src: 'PROJETOS/UPRADE/3.png', category: 'Rótulos', title: 'UPRADE' },
    { src: 'PROJETOS/UPRADE/4.png', category: 'Rótulos', title: 'UPRADE' },
    { src: 'PROJETOS/USALAB/1.png', category: 'Marcas', title: 'USALAB' },
    { src: 'PROJETOS/USALAB/10.png', category: 'Marcas', title: 'USALAB' },
    { src: 'PROJETOS/USALAB/11.png', category: 'Marcas', title: 'USALAB' },
    { src: 'PROJETOS/USALAB/2.png', category: 'Marcas', title: 'USALAB' },
    { src: 'PROJETOS/USALAB/3.png', category: 'Marcas', title: 'USALAB' },
    { src: 'PROJETOS/USALAB/4.png', category: 'Marcas', title: 'USALAB' },
    { src: 'PROJETOS/USALAB/5.png', category: 'Marcas', title: 'USALAB' },
    { src: 'PROJETOS/USALAB/6.png', category: 'Marcas', title: 'USALAB' },
    { src: 'PROJETOS/USALAB/7.png', category: 'Marcas', title: 'USALAB' },
    { src: 'PROJETOS/USALAB/8.png', category: 'Marcas', title: 'USALAB' },
    { src: 'PROJETOS/USALAB/9.png', category: 'Marcas', title: 'USALAB' }
];


